### ISSUE TITLE
ACPI error when using SSDT-EC-USBX.aml

### ISSUE THREAD

**Issue by rottenpants466** [dortania/Getting-Started-With-ACPI#1]
I was getting an ACPI error using SSDT-EC-USBX.aml correctly configured with my EC device, in my case H_EC. This was the error:

![acpi error](https://user-images.githubusercontent.com/62076029/79113608-2d22ed80-7d79-11ea-84e4-0d74eb4baa48.png)

I ended up checking my DSDT.aml again and found out that my H_EC device was already off like you can see in this picture:

![ec device](https://user-images.githubusercontent.com/62076029/79113569-17152d00-7d79-11ea-863e-856d4b44d181.png)

What I ended up doing with SSDT-EC-USBX.aml was removing the hiding H_EC device part and kept the usb power and the dummy EC device in the code:

![SSDT-EC-USBX](https://user-images.githubusercontent.com/62076029/79113780-9440a200-7d79-11ea-8808-5a47f9fb8a0d.png)

Now I no longer get that ACPI error. 

With this maybe we should add this information in the Embedded Controller section (desktop). First check if the EC device is active and if so then proceed to hide it. If it already returns 0 then there's no need for the hiding part.

My specs are:

MB: Z370 AORUS Gaming K3
CPU: i9 9900k
GPU: RX 580
16GB ram

[EFI.zip](https://github.com/dortania/Getting-Started-With-ACPI/files/4469151/EFI.zip)

[DSDT.aml.zip](https://github.com/dortania/Getting-Started-With-ACPI/files/4469172/DSDT.aml.zip)

cheers

**Comment by khronokernel** [comment]
Ah thank you for opening the issue, it was on my list of things to mention but slipped away a while ago. Also thank you for adding the nice crispy images, might steal one ;p

Fixed in latest commit: https://github.com/dortania/Getting-Started-With-ACPI/commit/9cb04fa336ae04ece25fd0ead42de4029eaf4ce1

**Comment by rottenpants466** [comment]
Cheers :)
