### ISSUE TITLE
Confusion in SSDT-PLUG instructions?

### ISSUE THREAD

**Issue by gavineadie** [dortania/Getting-Started-With-ACPI#11]
on page: https://dortania.github.io/Getting-Started-With-ACPI/Universal/plug.html

under: "Long Way(For those who want to learn)"

I believe there is an error (though I'll be the first to admit ACPI is new to me, I do want to learn).

It says, "As we can see, the first processor in our list is PR00. This is what we'll be applying the plugin-type=1 property too. Now grab SSDT-PLUG and replace the default CPU0 with our PR00."

The version of SSDT-PLUG that I downloaded, today, already has entries for `_SB_.PR00` and `_PR_.PR00` specifically 6th and 7th in the list:

    External (_SB_.CPU0, ProcessorObj)
    External (_PR_.CPU0, ProcessorObj)
    External (_PR_.CP00, ProcessorObj)
    External (_PR_.C000, ProcessorObj)
    External (_PR_.P000, ProcessorObj)
    External (_SB_.PR00, ProcessorObj)
    External (_PR_.PR00, ProcessorObj)
    External (_SB_.SCK0.CP00, ProcessorObj)
    External (_SB_.SCK0.PR00, ProcessorObj)

So, replacing the "default CPU0 with our PR00" makes duplicate entries (and a `dsl` that doesn't compile).  Would a more correct instruction be to delete the `_SB_.CPU0` and `_PR_.CPU0` (and associated later references), OR to move the `PR00` entries to the top of the list (assuming their order is significant)?

**Comment by khronokernel** [comment]
This was an issue with the page never updating to Acidanthera’s new SSDT-PLUG. The page has been rewritten with the new format in mind so should be a bit cleaner
