### ISSUE TITLE
Disable dGPU not works.

### ISSUE THREAD

**Issue by DilVika** [dortania/Getting-Started-With-ACPI#14]
I have just make a move from my exist Clover Hack to OC on my **GL552VX**. 
Everything seem work fine (except fn key, I think it relate to this problems somehow).
I followed  this [Disabling laptop dGPUs (SSDT-dGPU-Off/NoHybGfx)](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html) (with and without -wegnoegpu) and **got no work, prove by high temperature on system and high freq Fan**.
I dont know exactly, but compare to Clover, **there is a noticeable temperature difference**. So, I guess maybe there is some mistake in **guide** or **me**. I am trying to find out. It's very glad if I have just pointed at the right problems, if not, at least I can find out my mistake. 
[MyEFI](https://drive.google.com/file/d/1b49NcaBowuu54Dqsr5M_VEbntQpGjUyg/view?usp=sharing)
If someone know the problems, please tell me. Thank you.

**Comment by khronokernel** [comment]
Do have the system specs? Your full ACPI table dump? Clover EFI? 
There isn't much to work off of and not interested in trying to fetch info. There's also 2 SSDT methods mentioned and you haven't told us if you tried both or what you used previously on Clover.
Gonna close this issue for now, if there's an actual fault or edge case we need to account for I'm more than happy to open the issue up again
