### ISSUE TITLE
Advanced ACPI guide

### ISSUE THREAD

**Issue by dhinakg** [dortania/Getting-Started-With-ACPI#15]
Things to cover:

- [ ] Intro to ACPI
- [ ] Basic SSDT creation
- [ ] Hotpatch techniques
- [ ] Backlight/other function keys
- [ ] I2C fix
- [ ] Debugging/troubleshooting your ACPI
- [ ] Terminology

**Comment by khronokernel** [comment]
Closing as duplicate: https://github.com/dortania/bugtracker/issues/9
