### ISSUE TITLE
Changes in SSDT-PLUG

### ISSUE THREAD

**Issue by rottenpants466** [dortania/Getting-Started-With-ACPI#3]
Maybe you guys already know about about the changes made to SSDT-PLUG and what It needs to be changed in the guide but I still wanted to leave a few pics here in case you need it :)

So in my case the path is _PR and processor is PR00:

![scope:cpu](https://user-images.githubusercontent.com/62076029/79329161-334ad280-7f0f-11ea-8831-efb07af1f1b6.png)

Next I will simply remove the stuff that's not related to my system in the new SSDT-PLUG:

![edits](https://user-images.githubusercontent.com/62076029/79332065-16fd6480-7f14-11ea-8720-adc70b4cfd93.png)

The end result should look like this:

![results](https://user-images.githubusercontent.com/62076029/79332276-752a4780-7f14-11ea-94dc-4491372e4789.png)

cheers :)

**Comment by midi1996** [comment]
You're doing it wrong. The SSDT has `CondRefof` which will check if said device (in your case PR00) is present and if it does it will scope and add that _DSM method. The SSDT is meant to be used as it is, the added entries is made so that it automatically add the _DSM method as long as the device name checks out.

**Comment by midi1996** [comment]
![image](https://user-images.githubusercontent.com/4874726/79332913-8de72d00-7f15-11ea-954a-c90408f15296.png)
From the ACPI Spec 6.3 Jan 2019 https://uefi.org/sites/default/files/resources/ACPI_6_3_May16.pdf

**Comment by rottenpants466** [comment]
Oh I tought that I should remove the stuff that's not need like it's says on the top of the ssdt

![1](https://user-images.githubusercontent.com/62076029/79333807-0f8b8a80-7f17-11ea-8dbd-8caf1e8652a3.png)

So we just ignore that part and use it as it is without any edits?

thanks

**Comment by midi1996** [comment]
Tbh, it could be just from a cleaning up perspective, but the code would actually ignore if the said CPU device name doesnt exists.

**Comment by rottenpants466** [comment]
Yeah. Either way its easier to just compile and use it as is

Thanks again :)
