### ISSUE TITLE
[SUGGESTION] Add more infos about fixing some common AML errors and MaciASL patching grammar syntax

### ISSUE THREAD

**Issue by dreamwhite** [dortania/Getting-Started-With-ACPI#5]
As per title, getting a better overview of AML language syntax may be useful for those who wants to create custom patches. I've opened an issue inside @acidanthera bugtracker, issue [#799](https://github.com/acidanthera/bugtracker/issues/799). You can find more infos [here](https://github.com/acidanthera/MaciASL/blob/master/PATCH.md).

Some common errors maybe "unexpected closed paren", "case value already specified" etc...
Thx <3

**Comment by khronokernel** [comment]
Added in latest commit: 17f7c8a
Anything else to add, just list them here
