### ISSUE TITLE
Make it clear what options to use when using SSDTTime to patch IRQ Conflicts

### ISSUE THREAD

**Issue by DashLt** [dortania/Getting-Started-With-ACPI#6]
[The IRQ guide](https://dortania.github.io/Getting-Started-With-ACPI/Universal/irq.html) links to the SSDT: Easy page, which simply tells you to select the FixHPET option. However, this option gives the user 3 choices:
```
Current Legacy IRQs:

 - IPIC: [2]
 - MATH: [13]
 -  RTC: [8]
 - TIMR: [0]
 -  KBD: [1]
 -  MOU: [12]

C. Only Conflicitng IRQs from Legacy Devices (0,8,11 from IPIC/TMR/RTC)
O. Only Conflicting IRQs (0,8,11)
L. Legacy IRQs (from IPIC, TMR/TIMR, and RTC)
```
While there is a default option of C, the guide does not make it immediately clear which one to select. The advice I got was to select C, but someone more experienced with Hackintosh should add more information on which choice the user should select based on their circumstances.

**Comment by khronokernel** [comment]
Added a note: https://github.com/dortania/Getting-Started-With-ACPI/commit/ff1e71ee218215daf0dab85a148dd218b93517a2
